---
  - name:
    ansible.builtin.fail:
      msg: "the variable 'nutanix_pc_deploy_container_name' is not defined."
    when:
      - nutanix_pc_deploy_container_name is not defined

  - name:
    ansible.builtin.fail:
      msg: "the variable 'nutanix_pc_deploy_subnet_name' is not defined."
    when:
      - nutanix_pc_deploy_subnet_name is not defined

  - name:
    ansible.builtin.fail:
      msg: "the variable 'nutanix_pc_deploy_network_address' is not defined."
    when:
      - nutanix_pc_deploy_network_address is not defined

  - name:
    ansible.builtin.fail:
      msg: "the variable 'nutanix_pc_deploy_gateway' is not defined."
    when:
      - nutanix_pc_deploy_gateway is not defined

  - name:
    ansible.builtin.fail:
      msg: "the variable 'nutanix_pc_deploy_ip_address' is not defined."
    when:
      - nutanix_pc_deploy_ip_address is not defined

  - name:
    ansible.builtin.fail:
      msg: "the variable 'nutanix_pc_deploy_dns_list' is not defined."
    when:
      - nutanix_pc_deploy_dns_list is not defined
      - nutanix_pc_deploy_dns_list | length > 0
