---
- name: Deploy Prism Central
  block:
    - name: Deploying Prism Central to Cluster
      uri:
        url: "https://{{nutanix_host}}:{{nutanix_port}}/api/nutanix/v3/prism_central"
        method: POST
        validate_certs: "{{ validate_certs }}"
        body_format: json
        body: "{{ lookup('template','pc-req.j2') | from_yaml | to_json }}"
        headers:
          Authorization: "{{ nutanix_api_auth }}"
        status_code: 202
        return_content: yes
      register: nutanix_deploy_pc
      ignore_errors: False

    - name: Wait for Prism Central deploy task to complete
      ansible.builtin.import_role:
        name: grdavies.nutanix_role_prism_monitor_task
      vars:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        nutanix_debug: "{{ nutanix_debug }}"
        nutanix_task_uuid: "{{ nutanix_deploy_pc.json.task_uuid }}"
        nutanix_task_retries: "{{ nutanix_pc_deploy_retries }}"
        nutanix_task_retry_delay: "{{ nutanix_pc_deploy_delay }}"

    - set_fact:
      nutanix_pc_deploy_task: "{{ monitored_task }}"
