---
  - name: Generate basic authorization string for PC
    set_fact:
      nutanix_deploy_pc_tmp_auth_string: "admin:{{ nutanix_deploy_pc_default_password }}"
    no_log: True

  - name: Generate authorization header for PC
    set_fact:
      nutanix_deploy_pc_tmp_nutanix_api_auth: "Basic {{ nutanix_deploy_pc_tmp_auth_string | b64encode(encoding='ascii') }}"
    no_log: True

  - name: Set Prism Central "admin" user password
    uri:
      url: "https://{{ nutanix_deploy_pc_ip_address }}:{{ nutanix_port }}/PrismGateway/services/rest/v1/utils/change_default_system_password"
      method: POST
      validate_certs: "{{ validate_certs }}"
      body_format: json
      body:
        oldPassword: "{{ nutanix_deploy_pc_default_password }}"
        newPassword: "{{ nutanix_deploy_pc_new_password }}"
      headers:
        Authorization: "{{ nutanix_deploy_pc_tmp_nutanix_api_auth }}"
      status_code: 200
      return_content: yes
    register: nutanix_deploy_pc_initial_password
    ignore_errors: no

  - ansible.builtin.fail:
      msg: "the prism central 'admin' initial account password change failed."
    when:
      - not nutanix_deploy_pc_initial_password.json.value
