---
  - name: Find uuid for container "{{ nutanix_prism_deploy_pc_container_name }}"
    block:
      - name: Get containers from Prism API
        uri:
          url: "{{ nutanix_api_v2 }}/storage_containers"
          method: GET
          validate_certs: "{{ validate_certs }}"
          body_format: json
          headers:
            Authorization: "{{ nutanix_api_auth }}"
          status_code: 200
          return_content: yes
        register: nutanix_prism_current_containers
        ignore_errors: no

      - name: Search container list for container name and return its uuid
        set_fact:
          nutanix_prism_deploy_pc_container_uuid: "{{ item }}"
        with_items: "{{ nutanix_prism_current_containers.json | to_json | from_json | json_query(query) }}"
        vars:
          query: "entities[?name=='{{ nutanix_prism_deploy_pc_container_name }}'].storage_container_uuid"
        when: nutanix_prism_current_containers.json.metadata.total_entities > 0

  - name: Debug
    block:
      - name: Debug nutanix_prism_current_containers.json
        debug:
          var: nutanix_prism_current_containers.json

      - name: Debug nutanix_prism_deploy_pc_container_uuid
        debug:
          var: nutanix_prism_deploy_pc_container_uuid
    when:
      - nutanix_debug

  - ansible.builtin.fail:
      msg: "the container '{{ nutanix_prism_deploy_pc_container_name }}' was not found. Please check the input variable nutanix_prism_deploy_pc_container_name or that the container is present on this Nutanix cluster"
    when:
      - nutanix_prism_deploy_pc_container_uuid is not defined
